server:
  port: 8084
spring:
  application:
    name: voucher-service  #服务名称

hmdp:
  db:
    database: hmdp-voucher
  swagger:
    title: "黑马点评pro秒杀券接口文档"
    description: "黑马点评pro秒杀券接口文档"
    package: com.alfo.voucher.controller